### ISSUE TITLE
Prettytensor not working with TF1.8

### ISSUE THREAD

**Issue by YutingZhang** [google/prettytensor#62]
After upgrading to TF1.8, prettytensor stopped working with the following error. It seems _VARSCOPE_KEY is removed from variable_scope.

.../lib/python3.6/site-packages/prettytensor/scopes.py in var_and_name_scope(names)
     53         full_name = var_scope.name
     54
---> 55       vs_key = tf.get_collection_ref(variable_scope._VARSCOPE_KEY)
     56       try:
     57         # TODO(eiderman): Remove this hack or fix the full file.

AttributeError: module 'tensorflow.python.ops.variable_scope' has no attribute '_VARSCOPE_KEY'

**Comment by Saahiljeet-Singh** [comment]
@YutingZhang  Did you find the fix for this issue ?

**Comment by YutingZhang** [comment]
@Saahiljeet-Singh I have not looked into this issue. Instead, I simply downgraded TF to 1.7 ...

**Comment by akhilvasvani** [comment]
Change 
```tf.get_collection_ref(variable_scope._VARSCOPE_KEY)``` --> ```tf.get_collection_ref(variable_scope._VARSCOPESTORE_KEY)```

**Comment by affian** [comment]
Hey, after changing to tf.get_collection_ref(variable_scope._VARSCOPESTORE_KEY) I now have a new error: 

\Anaconda3\envs\Tensorflow_Project\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1349, in get_variable_scope
    return get_variable_scope_store().current_scope
AttributeError: 'VariableScope' object has no attribute 'current_scope'

**Comment by shine0318** [comment]
> Change `tf.get_collection_ref(variable_scope._VARSCOPE_KEY)` --> `tf.get_collection_ref(variable_scope._VARSCOPESTORE_KEY)`

After the change, the error is still reported
![image](https://user-images.githubusercontent.com/63570329/204465350-f9893550-4449-46b0-80f8-4de0880e135d.png)
